name: Build LaTeX document
on: 
  push:
    branches:
      - "master"
    paths:
      - "**"
    tags-ignore:
      - "*"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          path: "."
          files: |
            **/**.tex

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  build_latex:
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Change Name and NUSP
        # Probably there's a better way to do this (of doing this?, IDK, i dont speak freedom), but im not in the mood to search how to
        env:
          PERSON_1: ${{ secrets.PERSON_1 }}
          PERSON_ID_1: ${{ secrets.PERSON_ID_1 }}
          PERSON_2: ${{ secrets.PERSON_2 }}
          PERSON_ID_2: ${{ secrets.PERSON_ID_2 }}
          PERSON_3: ${{ secrets.PERSON_3 }}
          PERSON_ID_3: ${{ secrets.PERSON_ID_3 }}
          PERSON_4: ${{ secrets.PERSON_4 }}
          PERSON_ID_4: ${{ secrets.PERSON_ID_4 }}
          PERSON_5: ${{ secrets.PERSON_5 }}
          PERSON_ID_5: ${{ secrets.PERSON_ID_5 }}
          PERSON_6: ${{ secrets.PERSON_6 }}
          PERSON_ID_6: ${{ secrets.PERSON_ID_6 }}
        run: |
          sed -i "s/{{PERSON-1}}/$PERSON_1/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-1}}/$PERSON_ID_1/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-2}}/$PERSON_2/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-2}}/$PERSON_ID_2/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-3}}/$PERSON_3/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-3}}/$PERSON_ID_3/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-4}}/$PERSON_4/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-4}}/$PERSON_ID_4/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-5}}/$PERSON_5/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-5}}/$PERSON_ID_5/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-6}}/$PERSON_6/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-6}}/$PERSON_ID_6/g" ${{ matrix.files }}/resumo.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.files }}/resumo.tex
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.files }}
          path: ${{ matrix.files }}/resumo.pdf
          retention-days: 14
          overwrite: true
