name: Build LaTeX document
on: 
  push:
    branches:
      - '*'
    paths:
      - "**"
    tags-ignore:
      - "*"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          path: "."
          files: |
            **/**.tex

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  build_latex:
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Change Name and NUSP
        env:
          PERSON_2: ${{ secrets.PERSON_2 }}
          PERSON_ID_2: ${{ secrets.PERSON_ID_2 }}
        run: |
          sed -i "s/{{PERSON-2}}/$PERSON_2/g" ${{ matrix.files }}/resumo.tex
          sed -i "s/{{PERSON-ID-2}}/$PERSON_ID_2/g" ${{ matrix.files }}/resumo.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.files }}/resumo.tex
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.files }}
          path: ${{ matrix.files }}/resumo.pdf
          retention-days: 14
          overwrite: true
